Improved AimAssist
Coffee-Client/Coffee pull request #100
Opened 2024-02-19 18:36 UTC by RudideC

Added more smoothness, randomness and an option to change where to aim.
Feedback is appreciated

2024-02-20 07:39 UTC, 0x3C50 requested changes
code style and a few descriptions, otherwise great

2024-02-20 07:39 UTC, 0x3C50 commented on src/main/java/coffee/client/feature/module/impl/combat/AimAssist.java
> +        .description("Where to aim (in %)")
should probably elaborate on what that % affects

2024-02-20 07:39 UTC, 0x3C50 commented on src/main/java/coffee/client/feature/module/impl/combat/AimAssist.java
> +        .description("Whether or not the laziness should have randomness")
"Randomize speed when aiming"

2024-02-20 07:39 UTC, 0x3C50 commented on src/main/java/coffee/client/feature/module/impl/combat/AimAssist.java
> +        .description("The amount of randomness the lazyness should have")
"How strongly to affect speed when randomizing"

2024-02-20 07:39 UTC, 0x3C50 commented on src/main/java/coffee/client/feature/module/impl/combat/AimAssist.java
> +                    Rotations.lookAtPositionSmooth(le.getPos().add(0, (le.getHeight() / 1.3d), 0), (float) (modifiedLaziness));
should this look at the head of an entity? in which case `getEyePos()`

2024-02-20 07:39 UTC, 0x3C50 commented on src/main/java/coffee/client/feature/module/impl/combat/AimAssist.java
> +            }
surely this can be simplified down to avoid duplicate code

2024-02-20 07:39 UTC, 0x3C50 commented on src/main/java/coffee/client/feature/module/impl/combat/AimAssist.java
> +        }
same code but with a different variable, you can just use the modifiedLaziness and only change it when randomness is enabled

2024-02-20 16:04 UTC, RudideC commented
Ok fixed stuff now

2024-02-20 18:30 UTC, RudideC commented
By the way the createrelease.sh doesn't work, at least on mac

2024-02-20 22:01 UTC, 0x3C50 requested changes
took a proper look, didn't notice these things at first when going over the pr on mobile.
if you have a lot of duplicate code with only one variable or argument changing, it's best to remove the duplicate code and only actually change that one part. both of the if chains have a lot of duplicate code where you could just modify the position to look at. everything else is the same

2024-02-20 22:01 UTC, 0x3C50 commented on src/main/java/coffee/client/feature/module/impl/combat/AimAssist.java
> +            }
still code duplicates, you can use an enhanced switch here: 
```java
Rotation py = switch (aimMode.getValue()) {
    case AimMode.Top -> ...;
    case AimMode.Middle -> ...;
    ...
}
// use py
```

2024-02-20 22:01 UTC, 0x3C50 commented on src/main/java/coffee/client/feature/module/impl/combat/AimAssist.java
> +            }
enhanced switch might be best here too

2024-02-20 22:01 UTC, 0x3C50 commented on src/main/java/coffee/client/feature/module/impl/combat/AimAssist.java
> +        double modifiedLaziness = laziness.getValue() + 0;
this is a double, but any usages are casted to floats. probably better to make this a float and use Random#nextFloat for the offset

2024-02-20 22:40 UTC, RudideC commented
all right imma look into this tomorrow

2024-02-25 19:39 UTC, RudideC commented
ok i really haven't had time to do this so I will do it after my exams (i will work on it next thursday)

2025-11-04 18:01 UTC, closed without merging